### ISSUE TITLE
Maps - Dropdown-Auswahlmenü durchsuchbar machen

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/lasDB#1]
Bitte das Dropdown-Menü durchsuchbar machen - also wenn ich bsp. im Feld "Be.." eingebe, dass es mir zu den Karten, die mit "Be" beginnen, springt!

![image](https://user-images.githubusercontent.com/60658004/167618873-b0839593-7a5f-48e5-8f78-1f32652c27ce.png)

**Comment by hcb79** [comment]
Geht schon, funktioniert nur wegen den "Null" Maps, siehe #6 , nicht ... wird im anderen Issue behoben ... ;-)
