### ISSUE TITLE
Maps: Änderung default Einstellungen

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/lasDB#3]
John hätte gerne, dass die default-Einstellungen bei den Maps auf folgendes geändert werden:

Marker Source: Locations
Marker: Icons
Radius: 4 km

**Comment by hcb79** [comment]
Locations und Icons sind eine ganz schlechte Idee ... Aus Performance Sicht die schlechteste Wahl ... bei komplexeren Anfragen wie AnkleALL könnte der Browser des einen oder anderen Besuchers abschmieren ...
