### ISSUE TITLE
Maps: Read More für Descriptions?

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/lasDB#4]
Die Descriptions, die bei "Map to Variantgroups" von John in das Description-Field geschrieben werden, sind teilweise sehr lang - könnte man hier eventuell bei der Darstellung unter "Maps" ab einem gewissen Wordcount (vl. 350 oder 500 Wörter) ein "read more" oder so einfügen, die die Description erst auf Verlangen ganz aufklappt?

**Comment by hcb79** [comment]
Habe die Maximalhöhe angepasst. Wenn es höher ist muss man scrollen.
