### ISSUE TITLE
Maps: manche Maps nur für eingeloggte Benutzer?

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/lasDB#5]
Nur, falls das kein allzugroßer Aufwand ist - glaubst du könnte man bei den "Map to Variantgroup" vielleicht ein  Feld hinzufügen, dass die Sichtbarkeit der Karte nur für eingeloggte User einstellt? John erstellt relativ viele Karten, die er für seine Forschung braucht, die aber insgesamt relativ wenig aussagen, und die Liste an Karten ziemlich lang werden lässt - eventuell könnte man das verbessern, indem man manche Karten nur eingeloggten Usern zur Verfügung stellt (und die eben auch den nicht eingeloggten Usern im "Map"-Dropdown gar nicht anzeigt)?

**Comment by hcb79** [comment]
Mann muss die Karten dann freigeben. (public)
